# Generated by Django 3.2.9 on 2022-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_Name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
