# Generated by Django 3.2.9 on 2022-01-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_namecomapny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecomapny',
            old_name='NameComp',
            new_name='Company_Name',
        ),
    ]
