# Generated by Django 3.2.9 on 2022-02-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220209_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_employeer',
            new_name='is_employer',
        ),
    ]
