# Generated by Django 3.2.9 on 2022-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Job Seeker', 'JobSeeker'), ('Employer', 'Employer')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
