# Generated by Django 3.2.9 on 2022-02-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220210_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_type',
            new_name='User_Type',
        ),
    ]
