# Generated by Django 3.2.9 on 2022-04-22 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20220417_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='created_by',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='reciever',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth.user'),
            preserve_default=False,
        ),
    ]
