# Generated by Django 3.2.9 on 2021-12-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211211_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='img',
        ),
    ]
