# Generated by Django 3.2.9 on 2021-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20211212_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApllyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='apply_job/')),
                ('coverLetter', models.TextField(max_length=500)),
            ],
        ),
    ]
