# Generated by Django 3.2.9 on 2021-12-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apllyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apllyjob',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
