# Generated by Django 3.2.9 on 2021-12-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_apllyjob_website'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApllyJob',
            new_name='ApllayJob',
        ),
    ]
