# Generated by Django 3.2.9 on 2021-12-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_rename_apllyjob_apllayjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='apllayjob',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ApllayJob', to='job.job'),
            preserve_default=False,
        ),
    ]
