# Generated by Django 3.2.9 on 2022-02-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_alter_job_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apllayjob',
            old_name='website',
            new_name='portfolio_link',
        ),
    ]
