# Generated by Django 3.2.9 on 2022-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_rename_website_apllayjob_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apllayjob',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
