# Generated by Django 3.2.9 on 2022-02-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_auto_20220210_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='auto'),
        ),
    ]
