# Generated by Django 3.2.9 on 2022-02-15 02:31

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_alter_job_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.image_upload),
        ),
    ]
